package enough

var caTestCert = []byte(`
-----BEGIN CERTIFICATE-----
MIIBfTCCASSgAwIBAgIRAKxpQXQltTmMEBz8cVJ1w3IwCgYIKoZIzj0EAwIwLTEU
MBIGA1UEChMLSnVzdCBFbm91Z2gxFTATBgNVBAMTDFRlc3RDZXJ0cyBDQTAgFw0x
NDEwMDEwMTA3MDNaGA8yMTE0MTAwMTAxMDcwM1owLTEUMBIGA1UEChMLSnVzdCBF
bm91Z2gxFTATBgNVBAMTDFRlc3RDZXJ0cyBDQTBZMBMGByqGSM49AgEGCCqGSM49
AwEHA0IABHUHF2fjaMA97qT/0vapZ2IuKNA5GgM/LbpMqMBwR6s8sG0EpKqidLN0
J3BjsoGRghy34Csng8Tg1rsdI7WRNvyjIzAhMA4GA1UdDwEB/wQEAwIApDAPBgNV
HRMBAf8EBTADAQH/MAoGCCqGSM49BAMCA0cAMEQCIDjjXN9rEIbMEVAu0SFDxyvJ
sXRHl0avpROUFvOE7hh/AiBhSjYbohfDw1JSZ3Psz7Tc7plvx2ATIxISKMBaHxE+
fA==
-----END CERTIFICATE-----
`)

var serverTestCert = []byte(`
-----BEGIN CERTIFICATE-----
MIIBjjCCATOgAwIBAgIRAJTGaie8XKKOLMnppGwpJTkwCgYIKoZIzj0EAwIwLTEU
MBIGA1UEChMLSnVzdCBFbm91Z2gxFTATBgNVBAMTDFRlc3RDZXJ0cyBDQTAgFw0x
NDEwMDEwMTA3MDNaGA8yMTE0MTAwMTAxMDcwM1owKjEUMBIGA1UEChMLSnVzdCBF
bm91Z2gxEjAQBgNVBAMTCVRlc3RDZXJ0czBZMBMGByqGSM49AgEGCCqGSM49AwEH
A0IABLjTxuBmpzfqd1wpcdBohm1510JRA5gdY5OPltFb8x9GFj0ctxEOkodnxUSK
Ggg+zD29h6Sa1NPfQh4nP95aZIijNTAzMA4GA1UdDwEB/wQEAwIAoDATBgNVHSUE
DDAKBggrBgEFBQcDATAMBgNVHRMBAf8EAjAAMAoGCCqGSM49BAMCA0kAMEYCIQDc
sXNUtQVq8/wBgn6PhR7pJHGIhda8GVS/6sFUwyX7RQIhANeTAotHIOgEhCVKNHdM
x6hlcQyLX3Bf1t6RO88Z2ZMx
-----END CERTIFICATE-----
`)

var serverTestKey = []byte(`
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIIdWzPJP1OkbGGDGPJ9FWYdR5VaFGDa3zjbi5Nw6Gqf5oAoGCCqGSM49
AwEHoUQDQgAEuNPG4GanN+p3XClx0GiGbXnXQlEDmB1jk4+W0VvzH0YWPRy3EQ6S
h2fFRIoaCD7MPb2HpJrU099CHic/3lpkiA==
-----END EC PRIVATE KEY-----
`)

var clientTestCert = []byte(`
-----BEGIN CERTIFICATE-----
MIIBizCCATCgAwIBAgIQUNkDPUeBoIB/nTnYuA/e6jAKBggqhkjOPQQDAjAtMRQw
EgYDVQQKEwtKdXN0IEVub3VnaDEVMBMGA1UEAxMMVGVzdENlcnRzIENBMCAXDTE0
MTAwMTAxMDcwM1oYDzIxMTQxMDAxMDEwNzAzWjAoMRQwEgYDVQQKEwtKdXN0IEVu
b3VnaDEQMA4GA1UEAxMHQ2xpZW50MDBZMBMGByqGSM49AgEGCCqGSM49AwEHA0IA
BJE+Gyvm6d2WeubaWeTpCD4+aiEcODm2tO2GbuML/vvpPuFU3m1bV7L3pim6pam9
wHVakZTuueWFIAhF2Kdp556jNTAzMA4GA1UdDwEB/wQEAwIAoDATBgNVHSUEDDAK
BggrBgEFBQcDAjAMBgNVHRMBAf8EAjAAMAoGCCqGSM49BAMCA0kAMEYCIQDk7oK6
QixHXY7bqW4sl0xSr2GaIP8kM8JejQANnqWCyQIhAI2YxXLe9wb5rQqhBGmGus4V
ijdCNsxTk7nnJp7i13fv
-----END CERTIFICATE-----
`)

var clientTestKey = []byte(`
-----BEGIN EC PRIVATE KEY-----
MHcCAQEEIBTWPGLcNC7yJ8wtkNPWyEOXoiStLV5k2oFBJSpzXcm0oAoGCCqGSM49
AwEHoUQDQgAEkT4bK+bp3ZZ65tpZ5OkIPj5qIRw4Oba07YZu4wv+++k+4VTebVtX
svemKbqlqb3AdVqRlO655YUgCEXYp2nnng==
-----END EC PRIVATE KEY-----
`)
